apiVersion: v1
kind: Namespace
metadata:
  name: used-car-dealer
  labels:
    app: used-car-dealer
    environment: production
  annotations:
    description: "Namespace for Used Car Dealer Application"